### ISSUE TITLE
"Sign In" Button shows on lading page hamburger menu after sign in

### ISSUE THREAD

**Issue by leighbriody** [YourAverageTechBro/SWEProjects#30]
Hey tech bro , great project and would love to contribute , I have noticed a little possible issue , I have not looked into a fix to open a PR as currently I dont have time but . .. 

When you login first , when on mobile and on the landing page the hamburger menu still shows "sign in" even when signed in.

Steps to reproduce 
1. Go to landing page
2. Click sign in and login with google 
3. Redirects to landing page
4. Open hamburger menu (on mobile)
5. sign in button still shown even though I am signed in (slightly confusing)

**Comment by YourAverageTechBro** [comment]
Thanks so much for flagging this — will take a look.

**Comment by YourAverageTechBro** [comment]
For whoever takes this task, to set up authentication on your local instance, register for an account at [clerk.dev](clerk.dev), and then get the API keys and create an `.env` file and define these two env variables.

```
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=paste_your_publishable_key_here
CLERK_SECRET_KEY=paste_your_secret_key_here
```

Auth should work locally and you should be able to debug this issue afterwards. Reach out in the Discord if you need help still.
