### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by gilhrpenner** [YourAverageTechBro/SWEProjects#71]
Hey, was thinking about standardizing the components for consistency. I've been playing around with [CVA](https://github.com/joe-bell/cva) and thought it would be a good fit for sweprojets.

Thoughts? I could work on something.

**Comment by gilhrpenner** [comment]
Now I feel very conflicted. Mirrorful looks beautiful, I loved their dashboard to configure the colors, export tokens, etc. They also have an ESLint plugin that would definitely help with standardizing the code.

On the other hand, though, I don't see an easy way to make variations and the DX CVA offers is very close to [Stitches](https://stitches.dev/) which is the lib I felt the most productive and enjoyed working with.

Ultimately it is up to you, I am good with either :)

**Comment by YourAverageTechBro** [comment]
Let's go with what you're most comfortable with for now so CVA sounds great to me.

**Comment by gilhrpenner** [comment]
Life got a bit unexpected, will have to close this for the time being till I am more available 😢
